framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@paramall.tn'
        headers:
            from: 'Paramall <no-reply@paramall.tn>'
            bcc: 'notifications@paramall.tn'
            replyTo: 'contact@paramall.tn'
            X-Custom-Header: 'Paramall'