twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
      frontUrl : "http://localhost:3000"

when@test:
    twig:
        strict_variables: true
