vich_uploader:
    db_driver: orm

    mappings:
        img_upload:
            uri_prefix: /upload/img
            upload_destination: '%kernel.project_dir%/public/upload/img'
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
