
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://symfony:symfony@db:3306/symfony
    expose:
      - 8000

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
