[phases.setup]
nixPkgs = [
    "php74",
    "php74Extensions.curl",
    "php74Extensions.mbstring",
    "php74Extensions.intl",
    "php74Extensions.pdo_mysql",
    "php74Extensions.xml",
    "php74Extensions.zip",
    "php74Extensions.gd",
    "php74Extensions.xsl",
    "nodejs",
    "yarn",
]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer",
    "npm install -g yarn",
    "export COMPOSER_MEMORY_LIMIT=512M && php /bin/composer install --optimize-autoloader --ignore-platform-req=ext-xsl --no-scripts",
    "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
    "export NODE_OPTIONS=--openssl-legacy-provider && yarn build"
]

[start]
cmd = "sh -c 'echo \"Starting application without health check...\" && php /bin/composer run-script post-install-cmd && php bin/console cache:clear --no-warmup && php bin/console cache:warmup && php bin/console doctrine:migrations:migrate --no-interaction && echo \"Starting PHP server...\" && php -S 0.0.0.0:3000 -t public'"
