# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    compagnyName: "Paramall"
    compagnyAddress: "3 Rue Somaani cité Ennasim Ariana 2073, Tunis"
    compagnyCity: "Ariana"
    compagnyPhone: "28 122 180"
    compagnyEmail: "contact@paramall.tn"

    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    #acme_api.event.jwt_created_listener:
     #   class: App\EventListener\Auth\JWTCreatedListener
      #  arguments: [ '@request_stack' ]
       # tags:
        #    - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    
    acme_api.event.authentication_success_listener:
        class: App\EventListener\Auth\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }                

    'App\DataProvider\ProductDataProvider':
        arguments:
          $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

    'App\Doctrine\Product\ProductInDiscountExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }      

    App\Service\Aramex\Aramex:
        arguments:
            $compagnyName: '%compagnyName%'
            $compagnyAddress: '%compagnyAddress%'
            $compagnyCity: '%compagnyCity%'
            $compagnyPhone: '%compagnyPhone%'
            $compagnyEmail: '%compagnyEmail%'
    
    App\Service\Aramex\AramexPickUp:
        parent: App\Service\Aramex\Aramex
    
    App\Service\Aramex\AramexTracking:
        parent: App\Service\Aramex\Aramex


    # please note that last definitions always *replace* previous ones
